### ISSUE TITLE
0.3 does not build on Xcode 10 beta (10L176w)

### ISSUE THREAD

**Issue by shujew** [prebid/prebid-mobile-ios#77]
hey @ppuviarasu 

Can you please take a look at the error that I'm receiving while compiling 0.3 with Xcode 10 beta (10L176w)? Seems to be an issue with the new Xcode 10 build system.

```
error: Multiple commands produce '/.../Debug-iphoneos/PrebidMobile/PrebidMobile.framework/Headers/PrebidMobile-umbrella.h':
1) Target 'PrebidMobile' has copy command from '/.../Pods/PrebidMobile/sdk/PrebidMobile/PrebidMobile-umbrella.h' to '/.../Developer/Xcode/DerivedData/xxx-biwlmbnzlziimjdmmfuhrsqpkfic/Build/Products/Debug-iphoneos/PrebidMobile/PrebidMobile.framework/Headers/PrebidMobile-umbrella.h'
2) Target 'PrebidMobile' has copy command from '/.../Pods/Target Support Files/PrebidMobile/PrebidMobile-umbrella.h' to '/.../Developer/Xcode/DerivedData/xxx-biwlmbnzlziimjdmmfuhrsqpkfic/Build/Products/Debug-iphoneos/PrebidMobile/PrebidMobile.framework/Headers/PrebidMobile-umbrella.h'
```

Thanks

**Comment by ppuviarasu** [comment]
Hey @shujew 

I have tested the Prebidmobile SDK 5.0 on xcode 10.0 & the sdk builds fine.

Can you confirm the same.

Thanks

**Comment by ptomasroos** [comment]
Works great for us who has been involved since 0.0.1

**Comment by shujew** [comment]
@ppuviarasu I can confirm that this work as a temporary workaround. Hopefully, this issue can be addressed in the next release

**Comment by ppuviarasu** [comment]
Fixed in v 0.5.1

**Comment by ppuviarasu** [comment]
Are you integrating on the swift apps?

I tried this on the swift apps & Objective C apps & works fine...

**Comment by wacpenales** [comment]
Still reproducible after 0.5.1 
Even after deleting Pod cache and all.

Using cocoapod version 1.5.3.
Should we update the exclude statement to 
`s.exclude_files = "sdk/PrebidMobile/PrebidMobile-umbrella.h"` ?
